# Generated by Django 5.2.8 on 2025-12-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_verification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
