# Generated by Django 5.2.8 on 2026-04-03 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_last_verification_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresetcode',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='passwordresetcode',
            table='password_reset_codes',
        ),
    ]
