# Generated by Django 5.2.8 on 2026-04-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('USD', 'US Dollar'), ('GBP', 'British Pound'), ('EUR', 'Euro')], default='NGN', max_length=3),
        ),
    ]
